version: '3.9'

services:
  db:
    image: postgres
    container_name: actume_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: <db>
      POSTGRES_USER: <user>
      POSTGRES_PASSWORD: <password>
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - actume_network

volumes:
  pgdata:

networks:
  actume_network: